services:
  app:
    build:
      context: .
      dockerfile: Part_5/Dockerfile
    container_name: app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  proxy:
    image: nginx:alpine
    container_name: proxy
    depends_on:
      - app
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:8080"
